/**
 * Site-level naming and defaults for metadata (Jira 10308).
 *
 * `site-brand.ts` (Jira 10307) already owns *what the business is called*. This module owns the
 * handful of derived strings the metadata layer needs — the default title, the title template, the
 * default description, the locale — so that no route file writes a brand name as a literal again.
 *
 * Before this task the string "Otahuhu Printing" appeared as a hard-coded Open Graph suffix in five
 * route files and "Otahuhu Printing Shop" as a hard-coded `siteName` in six. Changing the public
 * identity (Jira 10300 A01/A02, still open) therefore meant a find-and-replace across the route
 * tree, with the usual chance of missing one. It is now one variable.
 *
 * Nothing here introduces a claim. No slogan is invented, no superlative is added, and
 * `brandLegalName` stays out of public metadata unless it is explicitly configured — a registered
 * entity name is not automatically a customer-facing one.
 */

import { brandFullName, brandLegalName, brandName } from '@/lib/site-brand'

export { brandFullName, brandLegalName, brandName }

/** `%s | Otahuhu Printing` by default. Applied by the root layout to every child route title. */
export const titleTemplate = `%s | ${brandName}`

/**
 * Homepage / fallback title.
 *
 * Reproduces the string the site already served. "Custom Printing Auckland" is a factual
 * description of what the shop does and where it is — it is not a ranking, quality or speed claim.
 */
export const defaultTitle = `${brandFullName} | Custom Printing Auckland`

/** Site-wide description. Lists what is printed; promises nothing about price, speed or coverage. */
export const defaultDescription =
  'Local Otahuhu print shop for T-shirt printing, badges, banners, business cards, stickers, signs and custom print jobs in Auckland.'

/** Shorter form for social cards, where long descriptions are truncated by the platform anyway. */
export const defaultSocialDescription =
  'T-shirts, badges, banners, business cards, stickers, signs and custom print jobs from a local Otahuhu print shop.'

export const siteLocale = 'en_NZ'
export const siteLanguage = 'en-NZ'

/**
 * The default social-sharing card.
 *
 * A committed 1200×630 PNG in `public/`, generated by `scripts/generate-og-image.mjs` — see that
 * file for why it is an asset rather than a generated `opengraph-image` route, and for what the card
 * deliberately does not contain (no logo, no favicon, no slogan, no photography, no legal name).
 *
 * It is referenced explicitly by {@link buildPageMetadata} rather than through the Next.js
 * `opengraph-image` file convention. The convention was tried first and was found not to reach
 * routes that declare their own `openGraph` block — which is every public route here — so only the
 * homepage carried a card. An explicit reference is one code path, applies everywhere, and is
 * directly assertable in a test.
 */
export const defaultSocialImage = {
  url: '/og-default.png',
  alt: `${brandFullName} — custom printing in Otahuhu, Auckland`,
  width: 1200,
  height: 630,
} as const

/** Open Graph `site_name`. */
export const openGraphSiteName = brandFullName

/** Suffix used for Open Graph titles, which do not honour the Next.js title template. */
export const socialTitle = (title: string): string =>
  title.includes(brandName) ? title : `${title} | ${brandName}`

/**
 * Search-engine ownership-verification tokens.
 *
 * Blank by default and never invented: a placeholder token renders a meta tag that claims ownership
 * of a property nobody has verified, and Search Console simply fails on it. Supplying a value here
 * only emits the tag — no external API is called and no property is verified by this code.
 */
export function verificationTokens(): { google?: string; bing?: string } {
  const google = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION?.trim()
  const bing = process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION?.trim()
  return {
    ...(google ? { google } : {}),
    ...(bing ? { bing } : {}),
  }
}
