// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TeeNova.EntityFrameworkCore;

#nullable disable

namespace TeeNova.Migrations
{
    [DbContext(typeof(TeeNovaDbContext))]
    [Migration("20260410120000_AddDesignNoteToOrderItem")]
    partial class AddDesignNoteToOrderItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
