// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeeNova.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace TeeNova.Migrations
{
    [DbContext(typeof(TeeNovaDbContext))]
    [Migration("20260408100000_AddCustomerNameAndAssetUrl")]
    partial class AddCustomerNameAndAssetUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("teenova")
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeeNova.Orders.Order", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("ConcurrencyStamp");
                    b.Property<DateTime>("CreationTime").HasColumnType("datetime2").HasColumnName("CreationTime");
                    b.Property<Guid?>("CreatorId").HasColumnType("uniqueidentifier").HasColumnName("CreatorId");
                    b.Property<string>("CustomerEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("CustomerName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<Guid?>("CustomerId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("DeleterId").HasColumnType("uniqueidentifier").HasColumnName("DeleterId");
                    b.Property<DateTime?>("DeletionTime").HasColumnType("datetime2").HasColumnName("DeletionTime");
                    b.Property<string>("ExtraProperties").IsRequired().HasColumnType("nvarchar(max)").HasColumnName("ExtraProperties");
                    b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false).HasColumnName("IsDeleted");
                    b.Property<DateTime?>("LastModificationTime").HasColumnType("datetime2").HasColumnName("LastModificationTime");
                    b.Property<Guid?>("LastModifierId").HasColumnType("uniqueidentifier").HasColumnName("LastModifierId");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("OrderNumber").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,4)");
                    b.HasKey("Id");
                    b.HasIndex("OrderNumber").IsUnique();
                    b.ToTable("Orders", "teenova");
                });

            modelBuilder.Entity("TeeNova.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("OrderId").HasColumnType("uniqueidentifier");
                    b.Property<string>("PrintPosition").HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<Guid>("ProductId").HasColumnType("uniqueidentifier");
                    b.Property<string>("ProductName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<Guid>("ProductVariantId").HasColumnType("uniqueidentifier");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,4)");
                    b.Property<Guid?>("UploadedAssetId").HasColumnType("uniqueidentifier");
                    b.Property<string>("UploadedAssetUrl").HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                    b.Property<string>("VariantLabel").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("OrderId");
                    b.ToTable("OrderItems", "teenova");
                });

            modelBuilder.Entity("TeeNova.Orders.Order", b =>
                {
                    b.OwnsOne("TeeNova.Orders.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AddressLine1").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                            b1.Property<string>("AddressLine2").HasMaxLength(512).HasColumnType("nvarchar(512)");
                            b1.Property<string>("City").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                            b1.Property<string>("Country").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                            b1.Property<string>("FullName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                            b1.Property<string>("Phone").HasMaxLength(32).HasColumnType("nvarchar(32)");
                            b1.Property<string>("PostalCode").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                            b1.Property<string>("State").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                            b1.HasKey("OrderId");
                            b1.ToTable("Orders", "teenova");
                            b1.WithOwner().HasForeignKey("OrderId");
                        });
                    b.Navigation("ShippingAddress").IsRequired();
                });

            modelBuilder.Entity("TeeNova.Orders.OrderItem", b =>
                {
                    b.HasOne("TeeNova.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeeNova.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
