import type { PublicContentDocument } from '@/lib/public-content/types'

/**
 * Privacy policy (Jira 10303).
 *
 * The sections describe the data flows that are actually implemented on this branch, so that the
 * page is accurate the moment it is approved rather than rewritten. It stays Draft because two
 * inputs do not exist: an approved retention period (also required before the quote workflow may
 * run at all) and legal review of the wording, legal basis and rights sections.
 *
 * The privacy contact address is resolved through configuration. Two mailbox addresses are valid
 * for the business, and which one is the privacy contact has not been decided, so no role is
 * assigned in content — see `privacyContactEmail` in `@/lib/site-contact`.
 */
export const privacyDocument: PublicContentDocument = {
  group: 'policies',
  slug: 'privacy',
  title: 'Privacy policy',
  description: 'What personal information Otahuhu Printing collects, why, and how it is handled.',
  classification: 'Policy',
  status: 'draft',
  approvalRequirement: 'owner-and-legal',
  draftReason:
    'No retention period has been approved and the policy has not been through legal review. Legal basis, individual rights, complaint handling and overseas-transfer wording cannot be written from the code.',
  related: [{ group: 'help', slug: 'artwork-requirements' }],
  sections: [
    {
      id: 'quote-request-data',
      heading: 'Information collected by the quote form',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference:
        'backend/src/TeeNova.Domain/Enquiries/QuoteRequest.cs; frontend/src/app/quote/quote-form-validation.ts',
      blocks: [
        {
          kind: 'list',
          items: [
            'Your name and email address, which are required.',
            'Your phone number and organisation name, if you choose to supply them.',
            'The service you selected and, where you arrived from a product page, the product our server matched.',
            'Quantity, width, height and unit, the date you need the work, and your pickup or delivery preference.',
            'The delivery suburb, when you choose delivery.',
            'Any notes you write.',
            'Any artwork files you attach.',
          ],
        },
        {
          kind: 'paragraph',
          text:
            'We also store technical values that stop the same request being recorded twice: a submission key generated by your browser, and checksums of the request details and attached files.',
        },
      ],
    },
    {
      id: 'network-address',
      heading: 'Your network address',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference: 'backend/src/TeeNova.Application/Enquiries/QuoteRequestAppService.cs',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'We do not store the IP address a quote request came from. Where a hashing key is configured, we store a one-way keyed hash of it so that abuse can be recognised without keeping the address itself. Rotating that key deliberately breaks the ability to match older records.',
        },
      ],
    },
    {
      id: 'artwork-storage',
      heading: 'Where your files are kept',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference:
        'backend/src/TeeNova.Domain/Enquiries/PrivateStorage/LocalQuotePrivateObjectStorage.cs; backend/src/TeeNova.Domain/Files/LocalFileStorageService.cs',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'Artwork attached to a quote request is stored privately, outside the public website folder, with no public web address. Only a signed-in administrator can retrieve it.',
        },
        {
          kind: 'paragraph',
          text:
            'A design uploaded from a product page or at checkout is stored in the website’s public uploads folder and is served as a static file, so it can be opened by anyone who has its address.',
        },
        {
          kind: 'paragraph',
          text:
            'We do not run malware scanning over uploaded files.',
        },
      ],
    },
    {
      id: 'orders-and-payment',
      heading: 'Orders and payment',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference:
        'backend/src/TeeNova.Domain/Orders/Order.cs; backend/src/TeeNova.Domain/Payments/OnlinePaymentSession.cs',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'When you place an order we store your name, email address, phone number where supplied, and the delivery address when the order is shipped. We store what you ordered and the amounts involved.',
        },
        {
          kind: 'paragraph',
          text:
            'Card details are never entered on this website. Online card payment happens on the payment provider’s own hosted page, and we receive only the outcome and the provider’s reference for it. We do not store card numbers.',
        },
      ],
    },
    {
      id: 'email-and-notifications',
      heading: 'Email',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference: 'backend/src/TeeNova.Application/Email',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'We send acknowledgement and notification emails through an email provider, which necessarily receives the address we are sending to and the content of the message.',
        },
      ],
    },
    {
      id: 'browser-storage',
      heading: 'Cookies and browser storage',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference:
        'frontend/src/features/products/configuration-persistence.ts; frontend/src/features/cart/cart-store.ts; frontend/src/app/api/auth/login/route.ts',
      blocks: [
        {
          kind: 'list',
          items: [
            'Your in-progress product configuration is kept in your browser’s session storage so a refresh does not lose it. Prices, artwork files, artwork addresses, notes and identity details are deliberately excluded from it, and it is cleared when you close the tab.',
            'Your cart contents are kept in your browser’s local storage so the cart survives a reload.',
            'A sign-in cookie is set only for staff administrators. Ordinary visitors are not given a sign-in cookie.',
          ],
        },
        {
          kind: 'paragraph',
          text:
            'The site does not use an analytics or tracking service, and no consent banner is shown because there is nothing to consent to.',
        },
      ],
    },
    {
      id: 'staff-access',
      heading: 'Who can see your information',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference: 'backend/src/TeeNova.HttpApi/Enquiries/QuoteRequestController.cs',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'Quote requests and orders are visible to signed-in staff. Administrators can change them and download attached artwork; accounts with read-only access can see the details but cannot change them or download files.',
        },
        {
          kind: 'paragraph',
          text:
            'Server logs record identifiers, references and outcomes rather than your contact details, notes, file names or network address.',
        },
      ],
    },
    {
      id: 'portfolio-media',
      heading: 'Photographs on this site',
      status: 'draft',
      factBasis: 'implemented-code',
      evidenceReference: 'backend/src/TeeNova.Domain/Portfolio',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'Photographs of previous work are business media that is published only after a permission record has been attached to it. Customer artwork is never reused as portfolio content automatically.',
        },
      ],
    },
    {
      id: 'retention',
      heading: 'How long information is kept',
      status: 'draft',
      factBasis: 'owner-approved',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'A retention period must be approved before this section can be published. The quote workflow will not run at all without a configured positive retention period, and that period drives the automatic removal of stored quote details and artwork. No period is assumed here.',
        },
      ],
    },
    {
      id: 'your-rights',
      heading: 'Your rights, legal basis and complaints',
      status: 'draft',
      factBasis: 'legal-approved',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'The legal basis for collection, your rights of access and correction, how a complaint is handled and whether any information is transferred overseas require legal review. Nothing is asserted here in advance of it.',
        },
      ],
    },
    {
      id: 'privacy-contact',
      heading: 'Contacting us about privacy',
      status: 'draft',
      factBasis: 'configurable',
      evidenceReference: 'frontend/src/lib/site-contact.ts (privacyContactEmail)',
      blocks: [
        {
          kind: 'paragraph',
          text:
            'The privacy contact address is supplied through site configuration. The business has two valid mailboxes and which of them handles privacy enquiries has not been decided, so no address is written into this policy.',
        },
      ],
    },
  ],
}
