'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { adminPortfolioApi,type PortfolioItem,type PortfolioStatus } from '@/api/portfolio'

export function PortfolioListClient({enabled,readOnly}:{enabled:boolean;readOnly:boolean}){
 const [items,setItems]=useState<PortfolioItem[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState<PortfolioStatus|''>(''),[service,setService]=useState(''),[error,setError]=useState<string|null>(null)
 useEffect(()=>{if(!enabled)return; let active=true; adminPortfolioApi.list({search:search||undefined,status:status||undefined,serviceType:service||undefined}).then(x=>{if(active)setItems(x.items)}).catch(e=>setError(e instanceof Error?e.message:'Could not load portfolio.')); return()=>{active=false}},[enabled,search,status,service])
 if(!enabled)return <div className="p-8"><h1 className="text-2xl font-medium">Portfolio</h1><p className="mt-3 text-sm text-black/55">Portfolio is disabled. Enable both backend and frontend flags only after approved media is ready.</p></div>
 return <div className="p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-medium">Portfolio</h1><p className="mt-1 text-sm text-black/50">Draft work stays private until an Admin publishes it.</p></div>{!readOnly&&<Link href="/admin/portfolio/new" className="btn-black">New item</Link>}</div>
 <div className="mt-6 flex flex-wrap gap-3"><label className="sr-only" htmlFor="portfolio-search">Search portfolio</label><input id="portfolio-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title or caption" className="rounded-lg border px-3 py-2 text-sm"/><label className="sr-only" htmlFor="portfolio-status">Status</label><select id="portfolio-status" value={status} onChange={e=>setStatus(e.target.value as PortfolioStatus|'')} className="rounded-lg border px-3 py-2 text-sm"><option value="">All statuses</option><option>Draft</option><option>Published</option><option>Archived</option></select><label className="sr-only" htmlFor="portfolio-service">Service</label><select id="portfolio-service" value={service} onChange={e=>setService(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">All services</option>{['GarmentPrinting','BringYourOwnGarment','Badges','Banners','BusinessCards','StickersLabels','Signage','Other'].map(x=><option key={x}>{x}</option>)}</select></div>
 {error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Title</th><th>Status</th><th>Images</th><th>Service</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="py-3"><Link href={`/admin/portfolio/${x.id}`} className="underline underline-offset-4">{x.title}</Link></td><td>{x.status}</td><td>{x.images.length}</td><td>{x.serviceType}</td></tr>)}</tbody></table></div></div>
}
