'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { adminPortfolioApi,type PortfolioDraft,type PortfolioImage,type PortfolioItem,type PortfolioPermissionSource } from '@/api/portfolio'

const SERVICES=['GarmentPrinting','BringYourOwnGarment','Badges','Banners','BusinessCards','StickersLabels','Signage','Other']
const empty:PortfolioDraft={title:'',slug:'',serviceType:'GarmentPrinting',shortCaption:'',longDescription:'',sortOrder:0,isFeatured:false}

export function PortfolioEditor({id,readOnly=false}:{id?:string;readOnly?:boolean}){
 const router=useRouter(),[item,setItem]=useState<PortfolioItem|null>(null),[form,setForm]=useState<PortfolioDraft>(empty),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null)
 useEffect(()=>{if(id)adminPortfolioApi.get(id).then(x=>{setItem(x);setForm(x)}).catch(e=>setError(e instanceof Error?e.message:'Could not load item.'))},[id])
 const set=<K extends keyof PortfolioDraft>(k:K,v:PortfolioDraft[K])=>setForm(x=>({...x,[k]:v}))
 async function save(){setBusy(true);setError(null);try{if(item){const next=await adminPortfolioApi.update(item.id,{...form,concurrencyStamp:item.concurrencyStamp??''});setItem(next)}else{const next=await adminPortfolioApi.create(form);router.replace(`/admin/portfolio/${next.id}`)} }catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 async function refresh(){if(id)setItem(await adminPortfolioApi.get(id))}
 async function action(kind:'publish'|'unpublish'|'archive'){if(!item)return;setBusy(true);setError(null);try{setItem(await adminPortfolioApi[kind](item.id))}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}}
 async function upload(file:File){if(!item)return;setBusy(true);try{await adminPortfolioApi.upload(item.id,file);await refresh()}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
 async function updateImage(image:PortfolioImage,patch:Partial<PortfolioImage>){if(!item)return;try{await adminPortfolioApi.updateImage(item.id,image.id,{altText:patch.altText??image.altText,permissionSource:patch.permissionSource??image.permissionSource,permissionReference:patch.permissionReference??image.permissionReference??'',sortOrder:patch.sortOrder??image.sortOrder,isPrimary:patch.isPrimary??image.isPrimary});await refresh()}catch(e){setError(e instanceof Error?e.message:'Image update failed.')}}
 async function remove(){if(!item||!confirm('Delete this portfolio item and its stored images? This cannot be undone.'))return;await adminPortfolioApi.delete(item.id);router.push('/admin/portfolio')}
 return <div className="p-6 sm:p-8"><h1 className="text-2xl font-medium">{item?'Edit portfolio item':'New portfolio item'}</h1>{item&&<p className="mt-1 text-sm text-black/50">Status: {item.status}</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
 <div className="mt-6 grid max-w-3xl gap-4 sm:grid-cols-2"><Field label="Title"><input value={form.title} onChange={e=>set('title',e.target.value)} required className="w-full rounded-lg border p-2"/></Field><Field label="Slug"><input value={form.slug} onChange={e=>set('slug',e.target.value.toLowerCase())} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required className="w-full rounded-lg border p-2"/></Field><Field label="Service"><select value={form.serviceType} onChange={e=>set('serviceType',e.target.value)} className="w-full rounded-lg border p-2">{SERVICES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Sort order"><input type="number" value={form.sortOrder} onChange={e=>set('sortOrder',Number(e.target.value))} className="w-full rounded-lg border p-2"/></Field><Field label="Short caption" wide><textarea value={form.shortCaption} maxLength={320} onChange={e=>set('shortCaption',e.target.value)} required className="w-full rounded-lg border p-2"/></Field><Field label="Long description" wide><textarea value={form.longDescription} onChange={e=>set('longDescription',e.target.value)} className="w-full rounded-lg border p-2"/></Field><label className="flex items-center gap-2"><input type="checkbox" checked={form.isFeatured} onChange={e=>set('isFeatured',e.target.checked)}/> Featured</label></div>
 {!readOnly&&<div className="mt-6 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void save()} className="btn-black">{busy?'Working…':'Save draft'}</button>{item&&<><button disabled={busy} onClick={()=>void action('publish')} className="btn-glass">Publish</button><button disabled={busy} onClick={()=>void action('unpublish')} className="btn-glass">Unpublish</button><button disabled={busy} onClick={()=>void action('archive')} className="btn-glass">Archive</button><button disabled={busy} onClick={()=>void remove()} className="rounded-full border border-red-300 px-5 py-2 text-red-700">Delete</button></>}</div>}
 {item&&<section className="mt-10"><h2 className="text-xl font-medium">Images</h2><p className="mt-1 text-sm text-black/50">JPEG, PNG or WebP. Metadata is removed and orientation normalized on upload.</p><p className="mt-2 text-sm" role="status">Publication checks: {item.images.length===0?'image required':item.images.some(x=>!x.altText.trim())?'alt text missing':item.images.some(x=>!x.permissionReference?.trim())?'permission evidence missing':item.images.filter(x=>x.isPrimary).length!==1?'select exactly one primary image':'image evidence complete'}</p>{!readOnly&&<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}} className="mt-4"/>}<div className="mt-5 space-y-5">{item.images.map(image=><ImageEditor key={image.id} itemId={item.id} image={image} readOnly={readOnly} onSave={updateImage} onDelete={async()=>{if(confirm('Delete this image?')){await adminPortfolioApi.deleteImage(item.id,image.id);await refresh()}}}/>)}</div></section>}</div>
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?'sm:col-span-2':''}><span className="mb-1 block text-sm text-black/60">{label}</span>{children}</label>}
// Draft previews must use the authenticated same-origin proxy; Next's server-side image optimizer
// cannot inherit the viewer's HttpOnly admin cookie.
// eslint-disable-next-line @next/next/no-img-element
function ImageEditor({itemId,image,readOnly,onSave,onDelete}:{itemId:string;image:PortfolioImage;readOnly:boolean;onSave:(image:PortfolioImage,patch:Partial<PortfolioImage>)=>Promise<void>;onDelete:()=>Promise<void>}){const [alt,setAlt]=useState(image.altText),[ref,setRef]=useState(image.permissionReference??''),[source,setSource]=useState<PortfolioPermissionSource>(image.permissionSource),[sort,setSort]=useState(image.sortOrder);return <div className="grid gap-4 rounded-lg border p-4 sm:grid-cols-[180px_1fr]"><img src={`/api/proxy/api/portfolio/admin/items/${itemId}/images/${image.id}/content`} alt={alt||'Draft preview'} className="h-40 w-full object-cover"/><div className="grid gap-3"><input disabled={readOnly} aria-label="Alt text" placeholder="Meaningful alt text" value={alt} onChange={e=>setAlt(e.target.value)} className="rounded-lg border p-2"/><select disabled={readOnly} aria-label="Permission source" value={source} onChange={e=>setSource(e.target.value as PortfolioPermissionSource)} className="rounded-lg border p-2"><option>BusinessOwned</option><option>CustomerPermission</option><option>Licensed</option></select><input disabled={readOnly} aria-label="Permission reference" placeholder="Date, photographer, approval or licence reference" value={ref} onChange={e=>setRef(e.target.value)} className="rounded-lg border p-2"/><input disabled={readOnly} aria-label="Sort order" type="number" value={sort} onChange={e=>setSort(Number(e.target.value))} className="rounded-lg border p-2"/><label className="flex items-center gap-2"><input disabled={readOnly} type="checkbox" checked={image.isPrimary} onChange={e=>void onSave(image,{isPrimary:e.target.checked})}/> Primary image</label>{!readOnly&&<div className="flex gap-2"><button onClick={()=>void onSave(image,{altText:alt,permissionSource:source,permissionReference:ref,sortOrder:sort})} className="btn-black">Save image</button><button onClick={()=>void onDelete()} className="text-sm text-red-700 underline">Delete image</button></div>}</div></div>}
