import { afterEach, describe, expect, it, vi } from 'vitest'

afterEach(() => { vi.unstubAllEnvs(); vi.resetModules() })

describe('site contact configuration', () => {
  it('defaults the quote feature off and preserves the existing email fallback', async () => {
    vi.stubEnv('NEXT_PUBLIC_QUOTE_FORM_ENABLED', '')
    vi.stubEnv('NEXT_PUBLIC_CONTACT_EMAIL', '')
    const contact = await import('./site-contact')
    expect(contact.quoteFormEnabled).toBe(false)
    expect(contact.quoteHref()).toBe('mailto:qualitycanvasltd@gmail.com')
  })
  it('builds a safe internal quote URL only when enabled', async () => {
    vi.stubEnv('NEXT_PUBLIC_QUOTE_FORM_ENABLED', 'true')
    const contact = await import('./site-contact')
    expect(contact.quoteHref({ service: 'banners', product: 'p1', source: '/products/p1' }))
      .toBe('/quote?service=banners&product=p1&source=%2Fproducts%2Fp1')
  })
  it('uses the owner-provided phone defaults and leaves optional messaging unset', async () => {
    vi.stubEnv('NEXT_PUBLIC_BUSINESS_PHONE', '')
    vi.stubEnv('NEXT_PUBLIC_BUSINESS_MOBILE', '')
    vi.stubEnv('NEXT_PUBLIC_WHATSAPP_NUMBER', '')
    vi.stubEnv('NEXT_PUBLIC_MESSENGER_URL', '')
    const contact = await import('./site-contact')
    expect(contact.businessPhone).toBe('(09) 270 3378')
    expect(contact.phoneHref).toBe('tel:092703378')
    expect(contact.businessMobile).toBe('027 276 7379')
    expect(contact.mobileHref).toBe('tel:0272767379')
    expect(contact.whatsappHref).toBeNull()
    expect(contact.messengerHref).toBeNull()
  })
  it('normalizes configured phone, mobile and WhatsApp URLs without changing display text', async () => {
    vi.stubEnv('NEXT_PUBLIC_BUSINESS_PHONE', '+64 9 123 4567')
    vi.stubEnv('NEXT_PUBLIC_BUSINESS_MOBILE', '+64 27 222 0101')
    vi.stubEnv('NEXT_PUBLIC_WHATSAPP_NUMBER', '+64 21 555 0101')
    const contact = await import('./site-contact')
    expect(contact.businessPhone).toBe('+64 9 123 4567')
    expect(contact.phoneHref).toBe('tel:+6491234567')
    expect(contact.businessMobile).toBe('+64 27 222 0101')
    expect(contact.mobileHref).toBe('tel:+64272220101')
    expect(contact.whatsappHref).toBe('https://wa.me/64215550101')
  })
  it('accepts only a specific secure Messenger contact URL', async () => {
    vi.stubEnv('NEXT_PUBLIC_MESSENGER_URL', 'https://m.me/otahuhuprint')
    const contact = await import('./site-contact')
    expect(contact.messengerHref).toBe('https://m.me/otahuhuprint')
    expect(contact.verifiedMessengerHref('https://www.messenger.com/t/otahuhuprint'))
      .toBe('https://www.messenger.com/t/otahuhuprint')
    expect(contact.verifiedMessengerHref('https://m.me/')).toBeNull()
    expect(contact.verifiedMessengerHref('http://m.me/otahuhuprint')).toBeNull()
    expect(contact.verifiedMessengerHref('https://example.com/otahuhuprint')).toBeNull()
  })
  it('uses a configured contact email consistently', async () => {
    vi.stubEnv('NEXT_PUBLIC_CONTACT_EMAIL', 'quotes@example.test')
    const contact = await import('./site-contact')
    expect(contact.contactEmail).toBe('quotes@example.test')
    expect(contact.emailHref).toBe('mailto:quotes@example.test')
  })
})
